### PR TITLE
Added function to draw custom markers with Kotlin DSL Canvas API

### PR DESCRIPTION
**Pull request by ArystanK**
FetureId can be extended to hold info about a feature??? I added unused onFeatureClick, which can be latter implemented with pointer input, where it will check coordinates with offset? Features need to hold info about their coordinates?

### CODE REVIEW

**Comment by altavir** [comment]
Feature could contain any additional data, including the callback, but in my opinion it should be handled outside of the map itself.  Map handles some callbacks like `onClick` (implemented), `onPan` (TODO)` and `onSelect`(also TODO).

**Comment by Lewik** [comment]
Custom MapFeature (not just access) with access to Canvas - nice idea, never thought about it.
As I think - MapFeature should holds graphical information only. Without any additional data. User should receive FeatureId and find additional data by himself.

I don't think MapFeature.onClick is good idea, we should leave MapView callback only. That onClick is not about graphic.

btw, we should have simple access to canvas too. Without MapFeature wrapping

**Review by Lewik — APPROVED** [review]

**Comment by altavir** [comment]
@ArystanK Ping me when it is ready to be merged.

**Review by altavir — APPROVED** [review]

**Comment by Lewik** [comment]
@ArystanK What is you custom marker? What is your use case for this feature?

**Pull request merged**
